name: Compile Changed Oracle Database Objects with Logs and Environments

on:
  push:
    branches:
      - main

jobs:
  compile-changed-objects:
    runs-on: ubuntu-latest

    # Use a Docker container with Oracle Instant Client pre-installed
    container:
      image: ghcr.io/kktest25/database_test_ai/oracle-client:latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4
    # install git in this step
    - name: Install Git
      run: |
       dnf install -y git
       git --version

    - name: Verify Oracle Linux Version
      run: cat /etc/os-release      

    # Step 2: Identify Changed Files
    - name: Get Changed Files
      id: changes
      run: |
        #echo "FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV
        FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) 
        echo "FILES=$FILES" >> $GITHUB_ENV

    # Step 3: Environment-Based Segregation
    - name: Set Environment Variables
      id: set-env
      run: |
        echo "${{ github.ref_name }}"

    # Step 4: Compile Changed Oracle Database Objects in Order and Log Output
    - name: Compile Changed Objects in Order
      run: |
        # Define execution order
        ORDERED_FOLDERS=("db1/VIEWS" "db1/MATERIALIZED_VIEWS" "db1/PACKAGES" "db1/PACKAGE_BODIES" "db1/SQL")
        
        # Create a log file
        LOG_FILE="execution_log_$(date +'%Y%m%d%H%M%S').log" 
        touch $LOG_FILE
        
        # Loop through folders in the predefined order
        for folder in "${ORDERED_FOLDERS[@]}"; do
          for file in $FILES; do
            if [[ $file == $folder/* ]]; then
              echo "Compiling $file in folder $folder" | tee -a $LOG_FILE
              if [[ $folder == db1/* ]]; then
                echo "Compiling $file in folder $folder" | tee -a >> $LOG_FILE 2>&1
              fi
            fi
          done
        done

    # Step 5: Upload Execution Log as Artifact
    - name: Upload Execution Log
      uses: actions/upload-artifact@v4
      with:
        name: execution-log
        path: $LOG_FILE
